apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITOPS_REPO.git
    path: gitops
    targetRevision: main
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
